### ISSUE TITLE
Need clarity in few steps  to run BigBWA

### ISSUE THREAD

**Issue by Nav15** [citiususc/BigBWA#6]
Hi Jose,
 There could be some mismatch  in steps  you mentioned and  which I actually followed . So can you please just go through below 3 steps/queries and  confirm each? Thanks for your time here.

**1:From which directory we should run the bellow commnad?**
hadoop jar BigBWA.jar -archives bwa.zip -D mapreduce.input.fileinputformat.split.minsize=123641127 -D mapreduce.input.fileinputformat.split.maxsize=123641127 -mem -paired -index /Data/HumanBase/hg19 -r ERR000589.fqBDP ExitERR000589

2:After running: hdfs dfs -copyFromLocal ERR000589.fqBDP ERR000589.fqBDP
 This  will place  the inpufile at directory:
/user/hadoop/ERR000030.fqBD  (hdfs path)
 ERR000589.fqBDP
**Is this correct or input file needs to be in some other place?**

3: Index is stored in all the cluster nodes(master node and datanodes) at:
  /Data/HumanBase

while  the  source code for BigBWA is at:
/home/hadoop/LS_Tools/BigBWA/

**Is this index path is correct in compare to BigBWA source code location?**

4: Also the space into   hadoop tmp(/home/hadoop/hadoop_tempdir) directory at master node is just 198M,  but as per document it should be 9GB. 
 So would this is required at every node or at only ,master node. Do you think that could also cause the Null Pointer Exception and not OutOfMemoryException?

**Comment by jmabuin** [comment]
1.- Inside BigBWA/build directory, wich is where the jar file and bwa.zip files are located
2.- It is correct if your execution command is the one from question 1, as you are specifying that the input is ERR000589.fqBDP
3.- The index location and the source code location are independent, so, yes, it is correct.
4.- You are going to need as much space as the input splits, so, yes, it can be the cause of the NulPointer Exception
