### ISSUE TITLE
Need help-Output  directory not generated in HDFS

### ISSUE THREAD

**Issue by Nav15** [citiususc/BigBWA#7]
Dear Jose,
 I am in last stage of getting the run  on my hadoop cluster and hence need few inputs to get through it:

I am able to run the application successfully and  below set of files generated on hdfs:
-rw-r--r--   1 hadoop hadoop   56118121 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input0_1.fq
-rw-r--r--   1 hadoop hadoop   56118121 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input0_2.fq
-rw-r--r--   1 hadoop hadoop   56199298 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input10_1.fq
-rw-r--r--   1 hadoop hadoop   56199298 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input10_2.fq
-rw-r--r--   1 hadoop hadoop   56199548 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input11_1.fq
-rw-r--r--   1 hadoop hadoop   56199548 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input11_2.fq
-rw-r--r--   1 hadoop hadoop   56199453 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input12_1.fq
-rw-r--r--   1 hadoop hadoop   56199453 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input12_2.fq
-rw-r--r--   1 hadoop hadoop   56199435 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input13_1.fq
-rw-r--r--   1 hadoop hadoop   56199435 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input13_2.fq
-rw-r--r--   1 hadoop hadoop   56199472 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input14_1.fq
-rw-r--r--   1 hadoop hadoop   56199472 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input14_2.fq
-rw-r--r--   1 hadoop hadoop   56199445 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input15_1.fq
-rw-r--r--   1 hadoop hadoop   56199445 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input15_2.fq
-rw-r--r--   1 hadoop hadoop   56199210 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input16_1.fq
-rw-r--r--   1 hadoop hadoop   56199210 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input16_2.fq
-rw-r--r--   1 hadoop hadoop   56199058 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input17_1.fq
-rw-r--r--   1 hadoop hadoop   56199058 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input17_2.fq
-rw-r--r--   1 hadoop hadoop   56199338 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input18_1.fq
-rw-r--r--   1 hadoop hadoop   56199338 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input18_2.fq
-rw-r--r--   1 hadoop hadoop   45892412 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input19_1.fq
-rw-r--r--   1 hadoop hadoop   45892412 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input19_2.fq
-rw-r--r--   1 hadoop hadoop   56136278 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input1_1.fq
-rw-r--r--   1 hadoop hadoop   56136278 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input1_2.fq
-rw-r--r--   1 hadoop hadoop   56183193 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input2_1.fq
-rw-r--r--   1 hadoop hadoop   56183193 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input2_2.fq
-rw-r--r--   1 hadoop hadoop   56199304 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input3_1.fq
-rw-r--r--   1 hadoop hadoop   56199304 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input3_2.fq
-rw-r--r--   1 hadoop hadoop   56199335 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input4_1.fq
-rw-r--r--   1 hadoop hadoop   56199335 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input4_2.fq
-rw-r--r--   1 hadoop hadoop   56199221 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input5_1.fq
-rw-r--r--   1 hadoop hadoop   56199221 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input5_2.fq
-rw-r--r--   1 hadoop hadoop   56199388 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input6_1.fq
-rw-r--r--   1 hadoop hadoop   56199388 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input6_2.fq
-rw-r--r--   1 hadoop hadoop   56199178 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input7_1.fq
-rw-r--r--   1 hadoop hadoop   56199178 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input7_2.fq
-rw-r--r--   1 hadoop hadoop   56199441 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input8_1.fq
-rw-r--r--   1 hadoop hadoop   56199441 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input8_2.fq
-rw-r--r--   1 hadoop hadoop   56199269 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input9_1.fq
-rw-r--r--   1 hadoop hadoop   56199269 2016-06-06 17:01 /user/hadoop/ExitERR000030/Input9_2.fq
-rw-r--r--   1 hadoop hadoop          0 2016-06-06 17:01 /user/hadoop/ExitERR000030/_SUCCESS
-rw-r--r--   1 hadoop hadoop          0 2016-06-06 17:01 /user/hadoop/ExitERR000030/part-r-00000

Issue I am facing:
**1: /user/hadoop/ExitERR000030/part-r-00000 generated with size 0KB.
2: No Output Output*.sam file not  created under : /user/hadoop/ExitERR000030/** and  size of file part-r-00000 is 0kb.

In application log it showing src and destination correctly:
2016-06-07 11:55:18,573 WARN [main] BigBWA: ****_copy results to HDFS local filesystem**_**
2016-06-07 11:55:18,573 WARN [main] BigBWA: ****_local file system, source outputFileName :::**_*_**/home/hadoop/hadoop_tempdir/Output0-26.sam_*
2016-06-07 11:55:18,573 WARN [main] BigBWA: ****_HDFS system, destination :::**_*_**/user/hadoop/ExitERR000030/Output0.sam_*

 How can I hold to see whether or not file generated on name node ,tmp directory(/home/hadoop/hadoop_tempdir)?

 I am using mem algorithm.

**Comment by jmabuin** [comment]
Hi @Nav15 ,

try to check your logs with **yarn logs -applicationId** and let me know the output

**Comment by Nav15** [comment]
Hi  jmabuin,
In tmp directory Output.sam file generating but with the 0kb size and on HDFS part-0000 is also   0KB.
There is no error or exception in  application log. Can you advise as what could be the reasons behind  data not getting written in .sam or part-r-0000 file?

**Comment by jmabuin** [comment]
I can not replicate the problem. Please, check if you have enough free space in your computing nodes.

**Comment by Nav15** [comment]
Thanks  jmabuin. can you please close this issue as well. Things are working as expected now.
