### ISSUE TITLE
Symbol lookup error while running bigBWA.jar

### ISSUE THREAD

**Issue by Vixz7** [citiususc/BigBWA#8]
HI,
We are trying to run bigBWA on our hadoop cluster of 7 nodes, we are using ECOLI dataset as provided with earlier version of bowtie ( e_coli_1000_1.fq and e_coli_1000_2.fq) and NC_008253.fna as reference genome. 
While submitting the command line we are getting the below error:
++++++---------------------------
/opt/java/jdk1.7.0_67/bin/java: symbol lookup error: /home/hadoop/hadoop_tempdir/nm-local-dir/usercache/hadoop/filecache/10/bwa.zip/libbwa.so: undefined symbol: gzdopen
---------------------------++++++

Please suggest if we are missing something while compiling or setting up the environment or any other source of error.

regards

**Comment by jmabuin** [comment]
Try adding library **-lz** in _Makefile.common_ to variable **LIBBWA_LIBS**

Your line will be **LIBBWA_LIBS = -lrt -lz**

Please, let me know if it works for you

**Comment by Vixz7** [comment]
Thanks jmabuin,
It worked for us after using LIBBWA_LIBS = -lrt -lz.. I will try it with a larger dataset (human genome)

regards,
